name: Terraform Apply

on:
  workflow_dispatch:  # 手動トリガー
    inputs:
      environment:
        description: 'Apply target environment'
        required: true
        type: choice
        options:
          - dev
          - prod

permissions:
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.4

      - name: Select workspace
        run: |
          terraform workspace select ${{ github.event.inputs.environment }} || terraform workspace new ${{ github.event.inputs.environment }}

      - name: Terraform Init
        run: terraform init -backend-config="key=terraform/${{ github.event.inputs.environment }}/state.tfstate"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1

      - name: Determine tfvars file
        run: echo "TFVARS=${{ github.event.inputs.environment }}.tfvars" >> $GITHUB_ENV

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=$TFVARS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1

      - name: Slack通知（Apply成功）
        uses: slackapi/slack-github-action@v1.23.0
        continue-on-error: true
        with:
          payload: |
            {
              "text": "Terraform Apply 成功"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
