name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Apply target environment'
        required: true
        type: choice
        options:
          - dev
          - prod

permissions:
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      ENV_NAME: ${{ github.event.inputs.environment }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-1

    concurrency:  # âœ… Applyã®æ’ä»–åˆ¶å¾¡ï¼ˆåŒã˜ç’°å¢ƒã§åŒæ™‚å®Ÿè¡Œã‚’é˜²æ­¢ï¼‰
      group: terraform-apply-${{ github.event.inputs.environment }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.4

      - name: Terraform Init
        run: terraform init -backend-config="key=terraform/state.tfstate"

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::903636036611:role/github-apply-log-writer
          aws-region: ap-northeast-1



      - name: Select Workspace
        run: terraform workspace select $ENV_NAME || terraform workspace new $ENV_NAME

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=${ENV_NAME}.tfvars > apply.log

      - name: Upload apply log to S3
        run: aws s3 cp apply.log s3://terraform-apply-logs/${{ github.run_id }}-${{ github.event.inputs.environment }}.log

      - name: Slacké€šçŸ¥ï¼ˆApplyæˆåŠŸï¼‰
        uses: slackapi/slack-github-action@v1.23.0
        continue-on-error: true
        with:
          payload: |
            {
              "text": "âœ… Terraform Apply æˆåŠŸ ğŸ‰\nğŸ“¦ ç’°å¢ƒ: ${{ github.event.inputs.environment }}\nğŸ‘¤ å®Ÿè¡Œè€…: ${{ github.actor }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
